name: Build LaTeX Document

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-latex:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Compile LaTeX document
      working-directory: ./src
      run: |
        echo "Starting LaTeX compilation..."
        echo "Working directory contents:"
        ls -la
        
        # First pass
        echo "Running first pdflatex pass..."
        pdflatex -interaction=nonstopmode -file-line-error main.tex  || true
        
        # Always run bibtex since references.bib exists
        echo "Running bibtex..."
        bibtex main
        
        # Second pass to resolve references
        echo "Running second pdflatex pass..."
        pdflatex -interaction=nonstopmode -file-line-error main.tex  || true
        
        # Third pass to ensure everything is resolved
        echo "Running third pdflatex pass..."
        pdflatex -interaction=nonstopmode -file-line-error main.tex || true
        
        echo "LaTeX compilation completed."
        
    - name: Show logs on compilation error
      if: failure()
      working-directory: ./src
      run: |
        echo "=== Compilation failed. Showing logs ==="
        if [ -f "main.log" ]; then
          echo "=== main.log ==="
          tail -50 main.log
        fi
        if [ -f "main.blg" ]; then
          echo "=== main.blg ==="
          cat main.blg
        fi
        
    - name: Check if PDF was created
      run: |
        if [ ! -f "src/main.pdf" ]; then
          echo "Error: PDF was not created"
          exit 1
        fi
        echo "PDF successfully created: $(ls -la src/main.pdf)"
        
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: latex-pdf
        path: src/main.pdf
        retention-days: 30
        
    - name: Upload compilation logs (on failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: latex-logs
        path: |
          src/*.log
          src/*.aux
          src/*.blg
        retention-days: 7
