name: Build LaTeX Document

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-latex:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Compile LaTeX document
      working-directory: ./src
      run: |
        echo "Starting LaTeX compilation..."
        echo "Working directory contents:"
        ls -la
        
        # First pass
        echo "Running first pdflatex pass..."
        pdflatex -interaction=nonstopmode -file-line-error main.tex  || true
        
        # Always run bibtex since references.bib exists
        echo "Running bibtex..."
        bibtex main
        
        # Second pass to resolve references
        echo "Running second pdflatex pass..."
        pdflatex -interaction=nonstopmode -file-line-error main.tex  || true
        
        # Third pass to ensure everything is resolved
        echo "Running third pdflatex pass..."
        pdflatex -interaction=nonstopmode -file-line-error main.tex || true
        
        echo "LaTeX compilation completed."
        
    - name: Show logs on compilation error
      if: failure()
      working-directory: ./src
      run: |
        echo "=== Compilation failed. Showing logs ==="
        if [ -f "main.log" ]; then
          echo "=== main.log ==="
          tail -50 main.log
        fi
        if [ -f "main.blg" ]; then
          echo "=== main.blg ==="
          cat main.blg
        fi
        
    - name: Check if PDF was created
      run: |
        if [ ! -f "src/main.pdf" ]; then
          echo "Error: PDF was not created"
          exit 1
        fi
        echo "PDF successfully created: $(ls -la src/main.pdf)"
        
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: latex-pdf-${{ github.sha }}
        path: src/main.pdf
        retention-days: 30
        
    - name: Comment on PR with artifact link
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
          const comment = `📄 **LaTeX PDF Generated**
          
          Your manuscript has been successfully compiled! 
          
          📥 **Download the PDF**: [View artifacts](${artifactUrl}) 
          
          The artifact will be available for 30 days.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
          
    - name: Upload compilation logs (on failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: latex-logs-${{ github.sha }}
        path: |
          src/*.log
          src/*.aux
          src/*.blg
        retention-days: 7

  release:
    needs: build-latex
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download PDF artifact
      uses: actions/download-artifact@v4
      with:
        name: latex-pdf-${{ github.sha }}
        
    - name: Rename PDF for release
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        mv main.pdf "sscita-assembly-manuscript-${TAG_NAME}.pdf"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: sscita-assembly-manuscript-*.pdf
        body: |
          ## 📄 Manuscript Release ${GITHUB_REF_NAME}
          
          This release contains the compiled PDF of the *Sporisorium scitamineum* genome assembly manuscript.
          
          ### 📥 Downloads
          - **PDF**: `sscita-assembly-manuscript-${GITHUB_REF_NAME}.pdf`

        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
